// src/TerminalInputBar.vue
<script setup lang="ts">
import { ref } from "vue";
import type { QuickButton } from "./settings";

const props = defineProps<{
  quickButtons: QuickButton[];
}>();

const emit = defineEmits<{
  send: [text: string];
  buttonsChange: [buttons: QuickButton[]];
  resize: [];
}>();

const SNAP_COLLAPSE_PX = 28;
const DEFAULT_TEXTAREA_H = 90;

const text = ref("");
const showEditor = ref(false);
const editButtons = ref<QuickButton[]>([]);
const textareaH = ref(DEFAULT_TEXTAREA_H);
const textareaRef = ref<HTMLTextAreaElement | null>(null);
let dragStartY = 0;
let dragStartH = 0;

function inputValue(event: Event) {
  return (event.target as HTMLInputElement | HTMLTextAreaElement).value;
}

function handleResizeMouseDown(event: MouseEvent) {
  event.preventDefault();
  dragStartY = event.clientY;
  dragStartH = textareaH.value;

  const handleMove = (moveEvent: globalThis.MouseEvent) => {
    const delta = dragStartY - moveEvent.clientY;
    const nextHeight = Math.max(0, dragStartH + delta);
    textareaH.value = nextHeight < SNAP_COLLAPSE_PX ? 0 : nextHeight;
  };

  const handleUp = () => {
    document.removeEventListener("mousemove", handleMove);
    document.removeEventListener("mouseup", handleUp);
    emit("resize");
  };

  document.addEventListener("mousemove", handleMove);
  document.addEventListener("mouseup", handleUp);
}

function handleResizeDblClick() {
  textareaH.value = textareaH.value === 0 ? DEFAULT_TEXTAREA_H : 0;
  emit("resize");
}

function doSend(payload: string) {
  if (!payload.trim()) {
    return;
  }
  emit("send", payload.endsWith("\n") ? payload : `${payload}\n`);
}

function handleKeyDown(event: KeyboardEvent) {
  if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) {
    event.preventDefault();
    doSend(text.value);
    text.value = "";
  }
}

function handleQuickButton(button: QuickButton) {
  doSend(button.command);
  textareaRef.value?.focus();
}

function openEditor() {
  editButtons.value = structuredClone(props.quickButtons);
  showEditor.value = true;
}

function saveEditor() {
  emit("buttonsChange", editButtons.value.filter((button) => button.label.trim() || button.command.trim()));
  showEditor.value = false;
}

function addButton() {
  editButtons.value = [...editButtons.value, { id: crypto.randomUUID(), label: "", command: "" }];
}

function updateButton(id: string, field: "label" | "command", value: string) {
  editButtons.value = editButtons.value.map((button) => (
    button.id === id ? { ...button, [field]: value } : button
  ));
}

function deleteButton(id: string) {
  editButtons.value = editButtons.value.filter((button) => button.id !== id);
}

function moveButton(id: string, direction: -1 | 1) {
  const index = editButtons.value.findIndex((button) => button.id === id);
  if (index < 0) {
    return;
  }
  const nextIndex = index + direction;
  if (nextIndex < 0 || nextIndex >= editButtons.value.length) {
    return;
  }
  const nextButtons = [...editButtons.value];
  [nextButtons[index], nextButtons[nextIndex]] = [nextButtons[nextIndex], nextButtons[index]];
  editButtons.value = nextButtons;
}

function closeEditor() {
  showEditor.value = false;
}
</script>

<template>
  <div class="terminal-input-bar">
    <div
      class="terminal-input-resize-handle"
      :class="{ collapsed: textareaH === 0 }"
      title="Drag to resize, double-click to collapse/expand"
      @mousedown="handleResizeMouseDown"
      @dblclick="handleResizeDblClick"
    >
      <span class="terminal-input-resize-grip" />
    </div>

    <div class="quick-buttons-bar">
      <button
        v-for="button in quickButtons"
        :key="button.id"
        class="quick-btn"
        type="button"
        :title="button.command"
        @click="handleQuickButton(button)"
      >
        {{ button.label.trim() || button.command.slice(0, 20) }}
      </button>

      <button class="quick-btn quick-btn--edit" type="button" title="Edit quick buttons" @click="openEditor">
        ✎ Edit
      </button>
    </div>

    <div v-if="textareaH > 0" class="terminal-input-row">
      <textarea
        ref="textareaRef"
        class="terminal-input-textarea"
        :style="{ height: `${textareaH}px` }"
        :value="text"
        placeholder="Type here…  Ctrl+Enter (⌘+Enter on macOS) to send"
        spellcheck="false"
        autocorrect="off"
        autocapitalize="off"
        @input="text = inputValue($event)"
        @keydown="handleKeyDown"
      />
      <button class="terminal-input-send-btn" type="button" title="Send  (Ctrl+Enter)" @click="doSend(text); text = ''">▶</button>
    </div>

    <div v-if="showEditor" class="quick-btn-editor-overlay" @click="closeEditor">
      <div class="quick-btn-editor" @click.stop>
        <div class="quick-btn-editor-header">
          <span>Edit Quick Buttons</span>
          <button type="button" class="quick-btn-editor-close" @click="closeEditor">×</button>
        </div>

        <div class="quick-btn-editor-body">
          <p v-if="editButtons.length === 0" class="quick-btn-editor-empty">
            No buttons yet — click <strong>+ Add</strong> to create one.
          </p>

          <div v-for="(button, index) in editButtons" :key="button.id" class="quick-btn-editor-row">
            <div class="quick-btn-editor-order">
              <button type="button" :disabled="index === 0" title="Move up" @click="moveButton(button.id, -1)">▲</button>
              <button
                type="button"
                :disabled="index === editButtons.length - 1"
                title="Move down"
                @click="moveButton(button.id, 1)"
              >
                ▼
              </button>
            </div>
            <input
              type="text"
              class="quick-btn-editor-input quick-btn-editor-input--label"
              placeholder="Label"
              :value="button.label"
              @input="updateButton(button.id, 'label', inputValue($event))"
            >
            <input
              type="text"
              class="quick-btn-editor-input quick-btn-editor-input--command"
              placeholder="Command  (e.g.  ls -la)"
              :value="button.command"
              @input="updateButton(button.id, 'command', inputValue($event))"
            >
            <button type="button" class="quick-btn-editor-delete" title="Delete" @click="deleteButton(button.id)">×</button>
          </div>
        </div>

        <div class="quick-btn-editor-footer">
          <button type="button" class="quick-btn-editor-add" @click="addButton">+ Add</button>
          <span style="flex: 1" />
          <button type="button" class="quick-btn-editor-cancel" @click="closeEditor">Cancel</button>
          <button type="button" class="quick-btn-editor-save" @click="saveEditor">Save</button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/TerminalInputBar.tsx
import { useState, useRef, useCallback, type KeyboardEvent, type MouseEvent } from "react";
import type { QuickButton } from "./settings";

interface TerminalInputBarProps {
  quickButtons: QuickButton[];
  onSend: (text: string) => void;
  onButtonsChange: (buttons: QuickButton[]) => void;
}

/** textarea 区域高度 < 这个值时自动折叠到 0 */
const SNAP_COLLAPSE_PX = 28;
/** 默认 textarea 高度（对应约 5 行） */
const DEFAULT_TEXTAREA_H = 90;

export function TerminalInputBar({ quickButtons, onSend, onButtonsChange }: TerminalInputBarProps) {
  const [text, setText] = useState("");
  const [showEditor, setShowEditor] = useState(false);
  const [editButtons, setEditButtons] = useState<QuickButton[]>([]);
  const [textareaH, setTextareaH] = useState(DEFAULT_TEXTAREA_H);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const dragStartY = useRef(0);
  const dragStartH = useRef(0);

  // ── Resize handle drag ──────────────────────────────────────────────────────
  const handleResizeMouseDown = useCallback((e: MouseEvent<HTMLDivElement>) => {
    e.preventDefault();
    dragStartY.current = e.clientY;
    dragStartH.current = textareaH;

    const onMove = (ev: globalThis.MouseEvent) => {
      // 向上拖 → 增大高度；向下拖 → 减小高度
      const delta = dragStartY.current - ev.clientY;
      const newH = Math.max(0, dragStartH.current + delta);
      setTextareaH(newH < SNAP_COLLAPSE_PX ? 0 : newH);
    };

    const onUp = () => {
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onUp);
    };

    document.addEventListener("mousemove", onMove);
    document.addEventListener("mouseup", onUp);
  }, [textareaH]);

  // 双击 handle：折叠 ↔ 展开
  const handleResizeDblClick = () => {
    setTextareaH((h) => (h === 0 ? DEFAULT_TEXTAREA_H : 0));
  };

  const doSend = (payload: string) => {
    if (!payload.trim()) return;
    onSend(payload.endsWith("\n") ? payload : payload + "\n");
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      doSend(text);
      setText("");
    }
  };

  const handleQuickButton = (btn: QuickButton) => {
    doSend(btn.command);
    textareaRef.current?.focus();
  };

  // ── Editor helpers ──────────────────────────────────────────────────────────
  const openEditor = () => {
    setEditButtons(structuredClone(quickButtons));
    setShowEditor(true);
  };

  const saveEditor = () => {
    onButtonsChange(editButtons.filter((b) => b.label.trim() || b.command.trim()));
    setShowEditor(false);
  };

  const addButton = () => {
    setEditButtons((prev) => [
      ...prev,
      { id: crypto.randomUUID(), label: "", command: "" },
    ]);
  };

  const updateButton = (id: string, field: "label" | "command", value: string) => {
    setEditButtons((prev) =>
      prev.map((b) => (b.id === id ? { ...b, [field]: value } : b))
    );
  };

  const deleteButton = (id: string) => {
    setEditButtons((prev) => prev.filter((b) => b.id !== id));
  };

  const moveButton = (id: string, dir: -1 | 1) => {
    setEditButtons((prev) => {
      const idx = prev.findIndex((b) => b.id === id);
      if (idx < 0) return prev;
      const next = idx + dir;
      if (next < 0 || next >= prev.length) return prev;
      const arr = [...prev];
      [arr[idx], arr[next]] = [arr[next], arr[idx]];
      return arr;
    });
  };

  return (
    <div className="terminal-input-bar">
      {/* ── Resize handle ─────────────────────────────────────────────────── */}
      <div
        className={`terminal-input-resize-handle${textareaH === 0 ? " collapsed" : ""}`}
        onMouseDown={handleResizeMouseDown}
        onDoubleClick={handleResizeDblClick}
        title="拖拽调整高度，双击折叠/展开"
      >
        <span className="terminal-input-resize-grip" />
      </div>

      {/* ── Quick buttons row ─────────────────────────────────────────────── */}
      <div className="quick-buttons-bar">
        {quickButtons.map((btn) => (
          <button
            key={btn.id}
            className="quick-btn"
            onClick={() => handleQuickButton(btn)}
            title={btn.command}
            type="button"
          >
            {btn.label.trim() || btn.command.slice(0, 20)}
          </button>
        ))}
        <button
          className="quick-btn quick-btn--edit"
          onClick={openEditor}
          title="Edit quick buttons"
          type="button"
        >
          ✎ Edit
        </button>
      </div>

      {/* ── Textarea + send button ─────────────────────────────────────────── */}
      {textareaH > 0 && (
        <div className="terminal-input-row">
          <textarea
            ref={textareaRef}
            className="terminal-input-textarea"
            style={{ height: textareaH }}
            value={text}
            onChange={(e) => setText(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Type here…  Ctrl+Enter (⌘+Enter on macOS) to send"
            spellCheck={false}
            autoCorrect="off"
            autoCapitalize="off"
          />
          <button
            className="terminal-input-send-btn"
            onClick={() => { doSend(text); setText(""); }}
            title="Send  (Ctrl+Enter)"
            type="button"
          >
            ▶
          </button>
        </div>
      )}

      {/* ── Quick-button editor dialog ─────────────────────────────────────── */}
      {showEditor && (
        <div
          className="quick-btn-editor-overlay"
          onClick={() => setShowEditor(false)}
        >
          <div
            className="quick-btn-editor"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="quick-btn-editor-header">
              <span>Edit Quick Buttons</span>
              <button
                type="button"
                className="quick-btn-editor-close"
                onClick={() => setShowEditor(false)}
              >
                ×
              </button>
            </div>

            <div className="quick-btn-editor-body">
              {editButtons.length === 0 && (
                <p className="quick-btn-editor-empty">
                  No buttons yet — click <strong>+ Add</strong> to create one.
                </p>
              )}
              {editButtons.map((btn, idx) => (
                <div key={btn.id} className="quick-btn-editor-row">
                  <div className="quick-btn-editor-order">
                    <button
                      type="button"
                      disabled={idx === 0}
                      onClick={() => moveButton(btn.id, -1)}
                      title="Move up"
                    >
                      ▲
                    </button>
                    <button
                      type="button"
                      disabled={idx === editButtons.length - 1}
                      onClick={() => moveButton(btn.id, 1)}
                      title="Move down"
                    >
                      ▼
                    </button>
                  </div>
                  <input
                    type="text"
                    placeholder="Label"
                    value={btn.label}
                    onChange={(e) => updateButton(btn.id, "label", e.target.value)}
                    className="quick-btn-editor-input quick-btn-editor-input--label"
                  />
                  <input
                    type="text"
                    placeholder="Command  (e.g.  ls -la)"
                    value={btn.command}
                    onChange={(e) => updateButton(btn.id, "command", e.target.value)}
                    className="quick-btn-editor-input quick-btn-editor-input--command"
                  />
                  <button
                    type="button"
                    className="quick-btn-editor-delete"
                    onClick={() => deleteButton(btn.id)}
                    title="Delete"
                  >
                    ×
                  </button>
                </div>
              ))}
            </div>

            <div className="quick-btn-editor-footer">
              <button
                type="button"
                className="quick-btn-editor-add"
                onClick={addButton}
              >
                + Add
              </button>
              <span style={{ flex: 1 }} />
              <button
                type="button"
                className="quick-btn-editor-cancel"
                onClick={() => setShowEditor(false)}
              >
                Cancel
              </button>
              <button
                type="button"
                className="quick-btn-editor-save"
                onClick={saveEditor}
              >
                Save
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
