// src/TerminalComponent.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { Terminal } from "xterm";
import { FitAddon } from "xterm-addon-fit";
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import { DEFAULT_SETTINGS, type AppSettings } from "./settings";
import type { SerialConnectionState, SessionConfig, SshConfig, TerminalHandle } from "./types";
import "xterm/css/xterm.css";

interface PtyOutputEvent {
  id: string;
  data: string;
}

interface PtyExitEvent {
  id: string;
  message: string;
}

interface SshMfaPrompt {
  text: string;
  echo: boolean;
}

interface SshMfaPromptEvent {
  id: string;
  name: string;
  instruction: string;
  prompts: SshMfaPrompt[];
}

const props = defineProps<{
  sessionId: string;
  isActive: boolean;
  session: SessionConfig;
  logPath?: string;
  settings?: AppSettings;
}>();

const emit = defineEmits<{
  serialConnectionStateChange: [state: SerialConnectionState];
}>();

function stripAnsi(value: string): string {
  return value
    .replace(/\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)/g, "")
    .replace(/\x1b\[[0-9;?]*[A-Za-z~]/g, "")
    .replace(/\x1b[^\[\]]/g, "")
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n");
}

function isAuthError(errorText: string): boolean {
  const lower = errorText.toLowerCase();
  return (
    lower.includes("authentication failed")
    || lower.includes("auth failed")
    || lower.includes("incorrect password")
    || lower.includes("permission denied")
  );
}

function formatLogTimestampParts(date = new Date()) {
  const pad = (value: number) => String(value).padStart(2, "0");
  const yyyy = String(date.getFullYear());
  const MM = pad(date.getMonth() + 1);
  const dd = pad(date.getDate());
  const HH = pad(date.getHours());
  const mm = pad(date.getMinutes());
  const ss = pad(date.getSeconds());
  const unix = String(Math.floor(date.getTime() / 1000));
  return {
    yyyy,
    MM,
    dd,
    HH,
    mm,
    ss,
    unix,
    date: `${yyyy}${MM}${dd}`,
    time: `${HH}${mm}${ss}`,
    timestamp: `${yyyy}${MM}${dd}_${HH}${mm}${ss}`,
  };
}

function resolveLogPathPlaceholders(path: string) {
  const parts = formatLogTimestampParts();
  return path
    .replace(/\{timestamp\}/g, parts.timestamp)
    .replace(/\{datetime\}/g, parts.timestamp)
    .replace(/\{date\}/g, parts.date)
    .replace(/\{time\}/g, parts.time)
    .replace(/\{yyyy\}/g, parts.yyyy)
    .replace(/\{MM\}/g, parts.MM)
    .replace(/\{dd\}/g, parts.dd)
    .replace(/\{HH\}/g, parts.HH)
    .replace(/\{mm\}/g, parts.mm)
    .replace(/\{ss\}/g, parts.ss)
    .replace(/\{unix\}/g, parts.unix);
}


function writeSessionInput(id: string, data: string, session: SessionConfig) {
  switch (session.protocol) {
    case "ssh":
      return invoke("write_ssh_pty_input", { id, data });
    case "telnet":
      return invoke("write_telnet_input", { id, data });
    case "serial":
      return invoke("write_serial_input", { id, data });
    case "local":
      return invoke("write_pty_input", { id, data });
  }
}

function resizeSession(id: string, cols: number, rows: number, session: SessionConfig) {
  switch (session.protocol) {
    case "ssh":
      return invoke("resize_ssh_pty", { id, cols, rows });
    case "local":
      return invoke("resize_pty", { id, cols, rows });
    case "telnet":
    case "serial":
      return Promise.resolve();
  }
}

function closeSession(id: string, session: SessionConfig) {
  switch (session.protocol) {
    case "ssh":
      return invoke("close_ssh_pty", { id });
    case "telnet":
      return invoke("close_telnet_session", { id });
    case "serial":
      return invoke("close_serial_session", { id });
    case "local":
      return invoke("close_pty", { id });
  }
}

const effectiveSettings = computed(() => props.settings ?? DEFAULT_SETTINGS);
const settingsRef = ref<AppSettings>(effectiveSettings.value);
const terminalRootRef = ref<HTMLDivElement | null>(null);
const ptyId = ref<string | null>(null);
const logBuffer = ref("");
const logPathRef = ref<string | undefined>(props.logPath);
const actualLogPath = ref<string | undefined>(undefined);
const activeSession = ref<SessionConfig>(props.session);
const activeSessionRef = ref<SessionConfig>(props.session);
const showRetryOverlay = ref(false);
const retryPassword = ref("");
const mfaEvent = ref<SshMfaPromptEvent | null>(null);
const mfaResponses = ref<string[]>([]);
const showMfaOverlay = ref(false);
const activeSshConfig = computed(() => (
  activeSession.value.protocol === "ssh" ? activeSession.value.sshConfig : undefined
));

let terminal: Terminal | null = null;
let fitAddon: FitAddon | null = null;
let terminalCleanup: (() => void) | null = null;
let stopSessionWatch: (() => void) | null = null;

watch(effectiveSettings, (value) => {
  settingsRef.value = value;
}, { deep: true, immediate: true });

watch(() => props.logPath, (value) => {
  logPathRef.value = value;
});

watch(() => props.session, (session) => {
  activeSession.value = session;
  showRetryOverlay.value = false;
  retryPassword.value = "";
  mfaEvent.value = null;
  mfaResponses.value = [];
  showMfaOverlay.value = false;
  if (session.protocol === "serial") {
    notifySerialConnectionStateChange("connecting");
  }
}, { deep: true });

watch(activeSession, (session) => {
  activeSessionRef.value = session;
}, { deep: true, immediate: true });

watch(effectiveSettings, (value) => {
  if (!terminal) {
    return;
  }
  terminal.options.fontSize = value.fontSize;
  terminal.options.fontFamily = value.fontFamily;
  terminal.options.scrollback = value.scrollback;
  terminal.options.theme = {
    background: value.theme.background,
    foreground: value.theme.foreground,
    cursor: value.theme.cursor,
  };
  fitAddon?.fit();
}, { deep: true });

watch(() => props.isActive, (isActive) => {
  if (!isActive) {
    return;
  }
  setTimeout(() => {
    fitAddon?.fit();
  }, 0);
});

function notifySerialConnectionStateChange(state: SerialConnectionState) {
  if (activeSessionRef.value.protocol === "serial") {
    emit("serialConnectionStateChange", state);
  }
}

async function saveLog(tabTitle: string) {
  const plain = stripAnsi(logBuffer.value);
  return invoke<string>("save_terminal_log", {
    content: plain,
    tabName: tabTitle,
  });
}

function sendData(text: string) {
  if (!ptyId.value) {
    return;
  }
  const id = ptyId.value;
  const data = text.endsWith("\n") ? text : `${text}\n`;
  void writeSessionInput(id, data, activeSessionRef.value).catch((error) => {
    console.error("sendData failed", error);
  });
}

function fit() {
  fitAddon?.fit();
}

defineExpose<TerminalHandle>({
  saveLog,
  sendData,
  fit,
});

onMounted(() => {
  if (!terminalRootRef.value) {
    return;
  }

  terminal = new Terminal({
    cursorBlink: true,
    cursorStyle: "block",
    fontFamily: effectiveSettings.value.fontFamily,
    fontSize: effectiveSettings.value.fontSize,
    scrollback: effectiveSettings.value.scrollback,
    theme: {
      background: effectiveSettings.value.theme.background,
      foreground: effectiveSettings.value.theme.foreground,
      cursor: effectiveSettings.value.theme.cursor,
    },
    convertEol: true,
    allowProposedApi: true,
    macOptionIsMeta: true,
  });

  fitAddon = new FitAddon();
  terminal.loadAddon(fitAddon);
  terminal.open(terminalRootRef.value);
  fitAddon.fit();

  terminal.attachCustomKeyEventHandler((event: KeyboardEvent) => {
    if (event.type !== "keydown") {
      return true;
    }

    if (event.ctrlKey && event.key === "c" && settingsRef.value.ctrlCCopy) {
      const selection = terminal?.getSelection();
      if (selection) {
        return false;
      }
    }

    if (event.ctrlKey && event.key === "v" && settingsRef.value.ctrlVPaste) {
      // Prevent default browser paste
      event.preventDefault();
      
      // Use xterm's paste method to avoid duplication
      void navigator.clipboard.readText().then((text) => {
        if (text && terminal) {
          // Use xterm's built-in paste which properly triggers onData
          terminal.paste(text);
        }
      }).catch((error) => {
        console.error("clipboard read failed", error);
      });
      
      return false; // Prevent default handling
    }

    return true;
  });

  const selectionDisposable = terminal.onSelectionChange(() => {
    if (!settingsRef.value.ctrlCCopy) {
      return;
    }
    const selection = terminal?.getSelection();
    if (!selection) {
      return;
    }
    void navigator.clipboard.writeText(selection).catch((error) => {
      console.error("clipboard write (selection) failed", error);
    });
  });

  const terminalElement = terminalRootRef.value;

  const handleMiddleMouseDown = (event: MouseEvent) => {
    if (event.button !== 1 || !settingsRef.value.middleClickPaste) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
  };

  const handleMiddleClick = (event: MouseEvent) => {
    if (event.button !== 1 || !settingsRef.value.middleClickPaste) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    void navigator.clipboard.readText().then((text) => {
      if (!text || !ptyId.value) {
        return;
      }
      void writeSessionInput(ptyId.value, text, activeSessionRef.value).catch((error) => {
        console.error("middle paste failed", error);
      });
    }).catch((error) => {
      console.error("clipboard read (middle click) failed", error);
    });
  };

  terminalElement.addEventListener("mousedown", handleMiddleMouseDown);
  terminalElement.addEventListener("auxclick", handleMiddleClick);

  const inputDisposable = terminal.onData((data) => {
    if (!ptyId.value) {
      return;
    }
    void writeSessionInput(ptyId.value, data, activeSessionRef.value).catch((error) => {
      console.error("input failed", error);
    });
  });

  const resizeDisposable = terminal.onResize(({ cols, rows }) => {
    if (!ptyId.value) {
      return;
    }
    void resizeSession(ptyId.value, cols, rows, activeSessionRef.value).catch((error) => {
      console.error("resize failed", error);
    });
  });

  const handleWindowResize = () => {
    fitAddon?.fit();
    if (!ptyId.value || !terminal) {
      return;
    }
    const cols = terminal.cols ?? 80;
    const rows = terminal.rows ?? 24;
    void resizeSession(ptyId.value, cols, rows, activeSessionRef.value).catch((error) => {
      console.error("resize on window resize failed", error);
    });
  };

  window.addEventListener("resize", handleWindowResize);

  terminalCleanup = () => {
    window.removeEventListener("resize", handleWindowResize);
    terminalElement.removeEventListener("mousedown", handleMiddleMouseDown);
    terminalElement.removeEventListener("auxclick", handleMiddleClick);
    selectionDisposable.dispose();
    inputDisposable.dispose();
    resizeDisposable.dispose();
    if (ptyId.value) {
      const id = ptyId.value;
      ptyId.value = null;
      void closeSession(id, activeSessionRef.value).catch(() => {});
    }
    terminal?.dispose();
    terminal = null;
    fitAddon = null;
  };

  stopSessionWatch = watch(activeSession, (session, _previous, onCleanup) => {
    let disposed = false;
    let unlistenOutput: UnlistenFn | null = null;
    let unlistenExit: UnlistenFn | null = null;
    let unlistenMfa: UnlistenFn | null = null;
    let unlistenSshConnected: UnlistenFn | null = null;
    let unlistenSerialConnected: UnlistenFn | null = null;

    const cleanup = () => {
      disposed = true;
      unlistenOutput?.();
      unlistenExit?.();
      unlistenMfa?.();
      unlistenSshConnected?.();
      unlistenSerialConnected?.();
      if (ptyId.value) {
        const id = ptyId.value;
        ptyId.value = null;
        void closeSession(id, session).catch(() => {});
      }
    };

    onCleanup(cleanup);

    const connect = async () => {
      if (!terminal) {
        return;
      }

      logBuffer.value = "";
      if (logPathRef.value) {
        const trimmedPath = logPathRef.value.trim();
        const resolvedPath = resolveLogPathPlaceholders(trimmedPath);
        actualLogPath.value = resolvedPath.endsWith(".log") ? resolvedPath : `${resolvedPath}.log`;
      } else {
        actualLogPath.value = undefined;
      }


      unlistenOutput = await listen<PtyOutputEvent>("pty-output", (event) => {
        if (event.payload.id !== ptyId.value || !terminal) {
          return;
        }
        terminal.write(event.payload.data);
        logBuffer.value += event.payload.data;
        if (actualLogPath.value) {
          const plain = stripAnsi(event.payload.data);
          void invoke("append_to_log", {
            path: actualLogPath.value,
            content: plain,
          }).catch((error) => {
            console.error("append_to_log failed", error);
          });
        }
      });

      unlistenExit = await listen<PtyExitEvent>("pty-exit", (event) => {
        if (event.payload.id !== ptyId.value || !terminal) {
          return;
        }
        const message = event.payload.message;
        terminal.writeln(`\r\n[Session exited] ${message}`);
        if (activeSessionRef.value.protocol === "serial") {
          notifySerialConnectionStateChange("closed");
        }
        if (activeSessionRef.value.protocol === "ssh" && isAuthError(message)) {
          ptyId.value = null;
          showRetryOverlay.value = true;
        }
      });

      unlistenSshConnected = await listen<{ id: string }>("ssh-connected", (event) => {
        if (event.payload.id === ptyId.value) {
          terminal?.writeln("\r\n[Connected]");
        }
      });

      unlistenSerialConnected = await listen<{ id: string }>("serial-connected", (event) => {
        if (event.payload.id === ptyId.value) {
          notifySerialConnectionStateChange("connected");
          terminal?.writeln("\r\n[Connected]");
        }
      });

      unlistenMfa = await listen<SshMfaPromptEvent>("ssh-mfa-prompt", (event) => {
        if (event.payload.id !== ptyId.value) {
          return;
        }
        mfaEvent.value = event.payload;
        mfaResponses.value = new Array(event.payload.prompts.length).fill("");
        showMfaOverlay.value = true;
      });

      if (disposed || !terminal) {
        unlistenOutput?.();
        unlistenExit?.();
        unlistenMfa?.();
        unlistenSshConnected?.();
        unlistenSerialConnected?.();
        return;
      }

      const cols = terminal.cols ?? 80;
      const rows = terminal.rows ?? 24;
      const newId = props.sessionId;
      ptyId.value = newId;

      try {
        switch (session.protocol) {
          case "ssh":
            terminal.writeln(`Connecting to ${session.sshConfig.user}@${session.sshConfig.host}:${session.sshConfig.port}...`);
            await invoke("start_ssh_pty", {
              id: newId,
              host: session.sshConfig.host,
              port: session.sshConfig.port,
              user: session.sshConfig.user,
              password: session.sshConfig.password ?? null,
              privateKey: session.sshConfig.privateKey ?? null,
              cols,
              rows,
            });
            break;
          case "telnet":
            terminal.writeln(`Connecting to telnet://${session.telnetConfig.host}:${session.telnetConfig.port}...`);
            await invoke("start_telnet_session", {
              id: newId,
              host: session.telnetConfig.host,
              port: session.telnetConfig.port,
            });
            terminal.writeln("\r\n[Connected]");
            break;
          case "serial":
            notifySerialConnectionStateChange("connecting");
            terminal.writeln(`Opening serial port ${session.serialConfig.portName} @ ${session.serialConfig.baudRate}...`);
            await invoke("start_serial_session", {
              id: newId,
              portName: session.serialConfig.portName,
              baudRate: session.serialConfig.baudRate,
              dataBits: session.serialConfig.dataBits,
              stopBits: session.serialConfig.stopBits,
              parity: session.serialConfig.parity,
              flowControl: session.serialConfig.flowControl,
            });
            break;
          case "local":
            terminal.writeln("Starting local shell PTY...");
            await invoke("start_pty", { id: newId, cols, rows });
            break;
        }
      } catch (error) {
        if (disposed || !terminal) {
          return;
        }
        ptyId.value = null;
        const errorText = String(error);
        if (session.protocol === "serial") {
          notifySerialConnectionStateChange("error");
        }
        terminal.writeln(`\r\n[Failed to start session] ${errorText}`);
        console.error("connect failed", error);
      }
    };

    void connect();
  }, { immediate: true, deep: true });
});

onBeforeUnmount(() => {
  stopSessionWatch?.();
  terminalCleanup?.();
});

function handlePasswordRetry(event: Event) {
  event.preventDefault();
  if (!activeSshConfig.value) {
    return;
  }
  const newConfig: SshConfig = { ...activeSshConfig.value, password: retryPassword.value };
  showRetryOverlay.value = false;
  retryPassword.value = "";
  activeSession.value = { protocol: "ssh", sshConfig: newConfig };
}

function handleMfaSubmit(event: Event) {
  event.preventDefault();
  if (!mfaEvent.value || !ptyId.value) {
    return;
  }
  void invoke("answer_ssh_mfa", {
    id: ptyId.value,
    responses: mfaResponses.value,
  });
  showMfaOverlay.value = false;
}

function updateMfaResponse(index: number, value: string) {
  const nextResponses = [...mfaResponses.value];
  nextResponses[index] = value;
  mfaResponses.value = nextResponses;
}

function inputValue(event: Event) {
  return (event.target as HTMLInputElement).value;
}

function handleCancelMfa() {
  showMfaOverlay.value = false;
  void invoke("answer_ssh_mfa", {
    id: ptyId.value,
    responses: mfaEvent.value?.prompts.map(() => "") ?? [],
  });
}
</script>

<template>
  <div
    :style="{
      position: 'relative',
      width: '100%',
      height: '100%',
      display: isActive ? 'flex' : 'none',
      flexDirection: 'column',
    }"
  >
    <div ref="terminalRootRef" :style="{ flex: 1, minHeight: 0 }" />

    <div v-if="showRetryOverlay && activeSshConfig" class="password-retry-overlay">
      <div class="password-retry-dialog">
        <div class="password-retry-icon">🔐</div>
        <h3 class="password-retry-title">Authentication Failed</h3>
        <p class="password-retry-desc">
          Could not connect to <strong>{{ activeSshConfig.user }}@{{ activeSshConfig.host }}</strong>.
          Incorrect password, please try again.
        </p>
        <form class="password-retry-form" @submit="handlePasswordRetry">
          <input
            v-model="retryPassword"
            type="password"
            class="password-retry-input"
            placeholder="Enter password"
            autofocus
            @keydown.stop
          >
          <div class="password-retry-actions">
            <button type="button" class="password-retry-btn cancel" @click="showRetryOverlay = false">Cancel</button>
            <button type="submit" class="password-retry-btn retry">Retry</button>
          </div>
        </form>
      </div>
    </div>

    <div v-if="showMfaOverlay && mfaEvent" class="password-retry-overlay">
      <div class="password-retry-dialog">
        <div class="password-retry-icon">🛡️</div>
        <h3 class="password-retry-title">{{ mfaEvent.name || 'MFA Required' }}</h3>
        <p class="password-retry-desc">{{ mfaEvent.instruction }}</p>
        <form class="password-retry-form" @submit="handleMfaSubmit">
          <div v-for="(prompt, index) in mfaEvent.prompts" :key="`${index}-${prompt.text}`" style="margin-bottom: 10px">
            <label style="display: block; margin-bottom: 5px; font-size: 12px; opacity: 0.8">{{ prompt.text }}</label>
            <input
              :type="prompt.echo ? 'text' : 'password'"
              class="password-retry-input"
              :value="mfaResponses[index] || ''"
              :autofocus="index === 0"
              :placeholder="prompt.text.replace(/[:：]\s*$/, '')"
              @input="updateMfaResponse(index, inputValue($event))"
              @keydown.stop
            >
          </div>
          <div class="password-retry-actions">
            <button type="button" class="password-retry-btn cancel" @click="handleCancelMfa">Cancel</button>
            <button type="submit" class="password-retry-btn retry">Verify</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

// src/TerminalComponent.tsx
import { useEffect, useRef, useState, forwardRef, useImperativeHandle, type FormEvent } from "react";
import { Terminal } from "xterm";
import { FitAddon } from "xterm-addon-fit";
import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import type { SshConfig } from "./ConnectDialog";
import type { AppSettings } from "./settings";
import { DEFAULT_SETTINGS } from "./settings";
import "xterm/css/xterm.css";

// ─── Public handle exposed via ref ─────────────────────────────────────────
export interface TerminalHandle {
  /** Strip ANSI codes and save buffered output to ~/AuraTerm/logs/. Returns the saved path. */
  saveLog: (tabTitle: string) => Promise<string>;
  /** Write raw data to the active PTY (e.g. a command string with trailing \n). */
  sendData: (text: string) => void;
}

/** Removes ANSI / VT escape sequences from a string. */
function stripAnsi(str: string): string {
  return str
    .replace(/\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)/g, "") // OSC sequences
    .replace(/\x1b\[[0-9;?]*[A-Za-z~]/g, "")            // CSI sequences
    .replace(/\x1b[^[\]]/g, "")                          // other ESC sequences
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n");
}

interface PtyOutputEvent {
  id: string;
  data: string;
}

interface PtyExitEvent {
  id: string;
  message: string;
}

interface SshMfaPrompt {
  text: string;
  echo: boolean;
}

interface SshMfaPromptEvent {
  id: string;
  name: string;
  instruction: string;
  prompts: SshMfaPrompt[];
}

interface TerminalComponentProps {
  isActive: boolean;
  sshConfig?: SshConfig;
  logPath?: string;
  settings?: AppSettings;
}

function isAuthError(errStr: string): boolean {
  const lower = errStr.toLowerCase();
  return (
    lower.includes("authentication failed") ||
    lower.includes("auth failed") ||
    lower.includes("incorrect password") ||
    lower.includes("permission denied")
  );
}

export const TerminalComponent = forwardRef<TerminalHandle, TerminalComponentProps>(
function TerminalComponent({ isActive, sshConfig, logPath, settings }, ref) {
  const effectiveSettings = settings ?? DEFAULT_SETTINGS;

  // 始终保持最新的 settings，供 Effect 1 内的事件处理器使用（避免闭包读取旧值）
  const settingsRef = useRef<AppSettings>(effectiveSettings);
  useEffect(() => {
    settingsRef.current = effectiveSettings;
  }, [settings]);

  const terminalRef = useRef<HTMLDivElement>(null);
  const term = useRef<Terminal | null>(null);
  const fitAddon = useRef<FitAddon | null>(null);
  const ptyIdRef = useRef<string | null>(null);
  /** Accumulates raw PTY output for the current session. */
  const logBufferRef = useRef<string>("");
  /** Base log path template provided by the caller (no timestamp, no extension). */
  const logPathRef = useRef<string | undefined>(logPath);
  useEffect(() => { logPathRef.current = logPath; }, [logPath]);
  /** Actual log file path for the current session (base + timestamp + .log). */
  const actualLogPathRef = useRef<string | undefined>(undefined);

  useImperativeHandle(ref, () => ({
    saveLog: async (tabTitle: string) => {
      const plain = stripAnsi(logBufferRef.current);
      const path = await invoke<string>("save_terminal_log", {
        content: plain,
        tabName: tabTitle,
      });
      return path;
    },
    sendData: (text: string) => {
      if (!ptyIdRef.current) return;
      const id = ptyIdRef.current;
      const data = text.endsWith("\n") ? text : text + "\n";
      if (activeSshConfigRef.current) {
        void invoke("write_ssh_pty_input", { id, data }).catch((e) => {
          console.error("write_ssh_pty_input sendData failed", e);
        });
      } else {
        void invoke("write_pty_input", { id, data }).catch((e) => {
          console.error("write_pty_input sendData failed", e);
        });
      }
    },
  }));

  // 内部活跃的 SSH 配置（密码重试时会更新）
  const [activeSshConfig, setActiveSshConfig] = useState<SshConfig | undefined>(sshConfig);
  // 供 Effect 1 的 event handler 读取最新 SSH 配置（避免闭包捕获旧值）
  const activeSshConfigRef = useRef<SshConfig | undefined>(sshConfig);

  // 密码重试 overlay
  const [showRetryOverlay, setShowRetryOverlay] = useState(false);
  const [retryPassword, setRetryPassword] = useState("");

  // MFA 验证对话框状态
  const [mfaEvent, setMfaEvent] = useState<SshMfaPromptEvent | null>(null);
  const [mfaResponses, setMfaResponses] = useState<string[]>([]);
  const [showMfaOverlay, setShowMfaOverlay] = useState(false);

  // 当 prop sshConfig 变化时（新连接），重置内部状态
  useEffect(() => {
    setActiveSshConfig(sshConfig);
    setShowRetryOverlay(false);
    setRetryPassword("");

    setMfaEvent(null);
    setMfaResponses([]);
    setShowMfaOverlay(false);
  }, [sshConfig]);

  // 同步 activeSshConfig 到 ref，供 Effect 1 的 handlers 使用
  useEffect(() => {
    activeSshConfigRef.current = activeSshConfig;
  }, [activeSshConfig]);

  // ─── Effect 1：初始化 xterm（只在 mount/unmount 时执行一次）────────────────
  useEffect(() => {
    if (!terminalRef.current) return;

    const terminal = new Terminal({
      cursorBlink: true,
      cursorStyle: "block",
      fontFamily: effectiveSettings.fontFamily,
      fontSize: effectiveSettings.fontSize,
      scrollback: effectiveSettings.scrollback,
      theme: {
        background: effectiveSettings.theme.background,
        foreground: effectiveSettings.theme.foreground,
        cursor: effectiveSettings.theme.cursor,
      },
      convertEol: true,
      allowProposedApi: true,
      macOptionIsMeta: true,
    });

    const fit = new FitAddon();
    terminal.loadAddon(fit);
    terminal.open(terminalRef.current);
    fit.fit();

    term.current = terminal;
    fitAddon.current = fit;

    // ─── 自定义键盘事件处理：Ctrl+C / Ctrl+V ─────────────────────────────────
    terminal.attachCustomKeyEventHandler((event: KeyboardEvent) => {
      if (event.type !== "keydown") return true;

      // Ctrl+C：有选中文本时消费事件（不发送 ^C 给 PTY），复制由 onSelectionChange 已处理
      if (event.ctrlKey && event.key === "c" && settingsRef.current.ctrlCCopy) {
        const selection = terminal.getSelection();
        if (selection) {
          // 选中内容已经由 onSelectionChange 写入剪贴板，直接消费按键即可
          return false;
        }
      }

      // Ctrl+V：从剪贴板粘贴到 PTY
      if (event.ctrlKey && event.key === "v" && settingsRef.current.ctrlVPaste) {
        void navigator.clipboard.readText().then((text) => {
          if (!text || !ptyIdRef.current) return;
          const id = ptyIdRef.current;
          if (activeSshConfigRef.current) {
            void invoke("write_ssh_pty_input", { id, data: text }).catch((e) => {
              console.error("write_ssh_pty_input paste failed", e);
            });
          } else {
            void invoke("write_pty_input", { id, data: text }).catch((e) => {
              console.error("write_pty_input paste failed", e);
            });
          }
        }).catch((e) => {
          console.error("clipboard read failed", e);
        });
        return false;
      }

      return true;
    });

    // ─── 选中即复制：每当 selection 变化时，若有内容则写入剪贴板 ──────────────
    const selectionDisposable = terminal.onSelectionChange(() => {
      if (!settingsRef.current.ctrlCCopy) return;
      const selection = terminal.getSelection();
      if (!selection) return;
      void navigator.clipboard.writeText(selection).catch((e) => {
        console.error("clipboard write (selection) failed", e);
      });
    });

    // ─── 鼠标中键粘贴 ──────────────────────────────────────────────────────
    const terminalEl = terminalRef.current;

    // mousedown 阶段就 preventDefault，阻止系统/浏览器弹出粘贴菜单
    const handleMiddleMouseDown = (event: MouseEvent) => {
      if (event.button !== 1) return;
      if (!settingsRef.current.middleClickPaste) return;
      event.preventDefault();
      event.stopPropagation();
    };

    // auxclick 在中键 release 后触发，此时执行实际粘贴
    const handleMiddleClick = (event: MouseEvent) => {
      if (event.button !== 1) return;
      if (!settingsRef.current.middleClickPaste) return;
      event.preventDefault();
      event.stopPropagation();
      void navigator.clipboard.readText().then((text) => {
        if (!text || !ptyIdRef.current) return;
        const id = ptyIdRef.current;
        if (activeSshConfigRef.current) {
          void invoke("write_ssh_pty_input", { id, data: text }).catch((e) => {
            console.error("write_ssh_pty_input middle paste failed", e);
          });
        } else {
          void invoke("write_pty_input", { id, data: text }).catch((e) => {
            console.error("write_pty_input middle paste failed", e);
          });
        }
      }).catch((e) => {
        console.error("clipboard read (middle click) failed", e);
      });
    };

    terminalEl.addEventListener("mousedown", handleMiddleMouseDown);
    terminalEl.addEventListener("auxclick", handleMiddleClick);

    // 输入 handler：通过 ref 读取当前的 activeSshConfig
    const inputDisposable = terminal.onData((data) => {
      if (!ptyIdRef.current) return;
      if (activeSshConfigRef.current) {
        void invoke("write_ssh_pty_input", { id: ptyIdRef.current, data }).catch((e) => {
          console.error("write_ssh_pty_input failed", e);
        });
      } else {
        void invoke("write_pty_input", { id: ptyIdRef.current, data }).catch((e) => {
          console.error("write_pty_input failed", e);
        });
      }
    });

    // resize handler
    const resizeDisposable = terminal.onResize(({ cols, rows }) => {
      if (!ptyIdRef.current) return;
      if (activeSshConfigRef.current) {
        void invoke("resize_ssh_pty", { id: ptyIdRef.current, cols, rows }).catch((e) => {
          console.error("resize_ssh_pty failed", e);
        });
      } else {
        void invoke("resize_pty", { id: ptyIdRef.current, cols, rows }).catch((e) => {
          console.error("resize_pty failed", e);
        });
      }
    });

    const handleWindowResize = () => {
      fit.fit();
      if (!ptyIdRef.current) return;
      const cols = terminal.cols ?? 80;
      const rows = terminal.rows ?? 24;
      if (activeSshConfigRef.current) {
        void invoke("resize_ssh_pty", { id: ptyIdRef.current, cols, rows }).catch((e) => {
          console.error("resize_ssh_pty on window resize failed", e);
        });
      } else {
        void invoke("resize_pty", { id: ptyIdRef.current, cols, rows }).catch((e) => {
          console.error("resize_pty on window resize failed", e);
        });
      }
    };
    window.addEventListener("resize", handleWindowResize);

    return () => {
      window.removeEventListener("resize", handleWindowResize);
      terminalEl.removeEventListener("mousedown", handleMiddleMouseDown);
      terminalEl.removeEventListener("auxclick", handleMiddleClick);
      selectionDisposable.dispose();
      inputDisposable.dispose();
      resizeDisposable.dispose();
      // 关闭 PTY（如果 Effect 2 cleanup 已经清空了 ptyIdRef，这里不会重复关闭）
      if (ptyIdRef.current) {
        const id = ptyIdRef.current;
        ptyIdRef.current = null;
        if (activeSshConfigRef.current) {
          void invoke("close_ssh_pty", { id }).catch(() => {});
        } else {
          void invoke("close_pty", { id }).catch(() => {});
        }
      }
      terminal.dispose();
      term.current = null;
      fitAddon.current = null;
    };
  }, []); // 空依赖：xterm 只初始化一次

  // ─── Effect 2：管理连接生命周期（依赖 activeSshConfig）────────────────────
  useEffect(() => {
    // xterm 可能还未初始化（Effect 1 尚未运行完）
    // 用 setTimeout 0 确保在 Effect 1 之后执行
    let disposed = false;
    let unlistenOutput: UnlistenFn | null = null;
    let unlistenExit: UnlistenFn | null = null;
    let unlistenMfa: UnlistenFn | null = null;
    let unlistenConnected: UnlistenFn | null = null;

    const connect = async () => {
      // 等待 xterm 初始化
      if (!term.current) {
        await new Promise<void>((resolve) => setTimeout(resolve, 50));
        if (disposed || !term.current) return;
      }

      // Reset log buffer and derive a fresh timestamped log path for this session
      logBufferRef.current = "";
      if (logPathRef.current) {
        const now = new Date();
        const pad = (n: number) => String(n).padStart(2, "0");
        const ts = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
        actualLogPathRef.current = `${logPathRef.current}_${ts}.log`;
      } else {
        actualLogPathRef.current = undefined;
      }

      unlistenOutput = await listen<PtyOutputEvent>("pty-output", (event) => {
        if (event.payload.id === ptyIdRef.current) {
          term.current?.write(event.payload.data);
          logBufferRef.current += event.payload.data;
          // 持续追加写入日志文件（过滤 ANSI 后）
          if (actualLogPathRef.current) {
            const plain = stripAnsi(event.payload.data);
            void invoke("append_to_log", {
              path: actualLogPathRef.current,
              content: plain,
            }).catch((e) => console.error("append_to_log failed", e));
          }
        }
      });
      unlistenExit = await listen<PtyExitEvent>("pty-exit", (event) => {
        if (event.payload.id === ptyIdRef.current) {
          const msg = event.payload.message;
          term.current?.writeln(`\r\n[PTY exited] ${msg}`);
          // 认证失败时弹出重试对话框
          if (activeSshConfig && isAuthError(msg)) {
            ptyIdRef.current = null;
            setShowRetryOverlay(true);
          }
        }
      });
      unlistenConnected = await listen<{ id: string }>("ssh-connected", (event) => {
        if (event.payload.id === ptyIdRef.current) {
          term.current?.writeln("\r\n[Connected]");
        }
      });
      unlistenMfa = await listen<SshMfaPromptEvent>("ssh-mfa-prompt", (event) => {
        if (event.payload.id === ptyIdRef.current) {
          setMfaEvent(event.payload);
          setMfaResponses(new Array(event.payload.prompts.length).fill(""));
          setShowMfaOverlay(true);
        }
      });

      if (disposed) {
        unlistenOutput();
        unlistenExit();
        unlistenMfa();
        unlistenConnected?.();
        return;
      }

      const cols = term.current?.cols ?? 80;
      const rows = term.current?.rows ?? 24;
      const newId = crypto.randomUUID();
      ptyIdRef.current = newId;

      try {
        if (activeSshConfig) {
          term.current?.writeln(
            `Connecting to ${activeSshConfig.user}@${activeSshConfig.host}:${activeSshConfig.port}...`
          );
          await invoke<string>("start_ssh_pty", {
            id: newId,
            host: activeSshConfig.host,
            port: activeSshConfig.port,
            user: activeSshConfig.user,
            password: activeSshConfig.password ?? null,
            privateKey: activeSshConfig.privateKey ?? null,
            cols,
            rows,
          });
          // [Connected] 由后端 ssh-connected 事件触发，不在这里写
        } else {
          term.current?.writeln("Starting local shell PTY...");
          await invoke<string>("start_pty", { id: newId, cols, rows });
        }
      } catch (error) {
        if (disposed) return;
        ptyIdRef.current = null;
        const errStr = String(error);
        term.current?.writeln(`\r\n[Failed to start PTY] ${errStr}`);
        console.error("connect failed", error);
      }
    };

    void connect();

    return () => {
      disposed = true;
      unlistenOutput?.();
      unlistenExit?.();
      unlistenMfa?.();
      unlistenConnected?.();
      // 关闭当前 PTY 连接（activeSshConfig 变化时触发，用于关闭旧连接）
      if (ptyIdRef.current) {
        const id = ptyIdRef.current;
        ptyIdRef.current = null;
        if (activeSshConfig) {
          void invoke("close_ssh_pty", { id }).catch(() => {});
        } else {
          void invoke("close_pty", { id }).catch(() => {});
        }
      }
    };
  }, [activeSshConfig]); // activeSshConfig 变化时重新连接（密码重试、新连接）


  // ─── 动态应用 settings 变化（不重启 PTY）─────────────────────────────────
  useEffect(() => {
    if (!term.current || !settings) return;
    term.current.options.fontSize = settings.fontSize;
    term.current.options.fontFamily = settings.fontFamily;
    term.current.options.scrollback = settings.scrollback;
    term.current.options.theme = {
      background: settings.theme.background,
      foreground: settings.theme.foreground,
      cursor: settings.theme.cursor,
    };
    fitAddon.current?.fit();
  }, [settings]);

  // ─── 激活时调整大小──────────────────────────────────────────────────────
  useEffect(() => {
    if (isActive) {
      setTimeout(() => {
        fitAddon.current?.fit();
      }, 0);
    }
  }, [isActive]);

  // ─── 密码重试处理────────────────────────────────────────────────────────
  const handlePasswordRetry = (e: FormEvent) => {
    e.preventDefault();
    if (!activeSshConfig) return;
    const newConfig: SshConfig = { ...activeSshConfig, password: retryPassword };
    setShowRetryOverlay(false);
    setRetryPassword("");
    setActiveSshConfig(newConfig);
  };

  const handleMfaSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (!mfaEvent || !ptyIdRef.current) return;
    void invoke("answer_ssh_mfa", {
      id: ptyIdRef.current,
      responses: mfaResponses,
    });
    setShowMfaOverlay(false);
  };

  return (
    <div
      style={{
        position: "relative",
        width: "100%",
        height: "100%",
        display: isActive ? "flex" : "none",
        flexDirection: "column",
      }}
    >
      <div ref={terminalRef} style={{ flex: 1, minHeight: 0 }} />

      {showRetryOverlay && activeSshConfig && (
        <div className="password-retry-overlay">  
          <div className="password-retry-dialog">
            <div className="password-retry-icon">🔐</div>
            <h3 className="password-retry-title">认证失败</h3>
            <p className="password-retry-desc">
              无法连接到 <strong>{activeSshConfig.user}@{activeSshConfig.host}</strong>，
              密码不正确，请重新输入。
            </p>
            <form onSubmit={handlePasswordRetry} className="password-retry-form">
              <input
                type="password"
                className="password-retry-input"
                value={retryPassword}
                onChange={(e) => setRetryPassword(e.target.value)}
                placeholder="输入密码"
                onKeyDown={(e) => e.stopPropagation()}
                autoFocus
              />
              <div className="password-retry-actions">
                <button
                  type="button"
                  className="password-retry-btn cancel"
                  onClick={() => setShowRetryOverlay(false)}
                >
                  取消
                </button>
                <button type="submit" className="password-retry-btn retry">
                  重试连接
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {showMfaOverlay && mfaEvent && (
        <div className="password-retry-overlay">  
          <div className="password-retry-dialog">
            <div className="password-retry-icon">🛡️</div>
            <h3 className="password-retry-title">{mfaEvent.name || "需要两步验证"}</h3>
            <p className="password-retry-desc">{mfaEvent.instruction}</p>
            <form onSubmit={handleMfaSubmit} className="password-retry-form">
              {mfaEvent.prompts.map((prompt, index) => (
                <div key={index} style={{ marginBottom: "10px" }}>
                  <label style={{ display: "block", marginBottom: "5px", fontSize: "12px", opacity: 0.8 }}>
                    {prompt.text}
                  </label>
                  <input
                    type={prompt.echo ? "text" : "password"}
                    className="password-retry-input"
                    value={mfaResponses[index] || ""}
                    onChange={(e) => {
                      const newResponses = [...mfaResponses];
                      newResponses[index] = e.target.value;
                      setMfaResponses(newResponses);
                    }}
                    onKeyDown={(e) => {
                      // 阻止事件冒泡到 xterm，防止回退键、空格等触发终端行为
                      e.stopPropagation();
                    }}
                    autoFocus={index === 0}
                    placeholder={prompt.text.replace(/[:：]\s*$/, "")}
                  />
                </div>
              ))}
              <div className="password-retry-actions">
                <button
                  type="button"
                  className="password-retry-btn cancel"
                  onClick={() => {
                    setShowMfaOverlay(false);
                    // 发送空响应或取消标识，后端会因认证失败而退出
                    void invoke("answer_ssh_mfa", {
                      id: ptyIdRef.current,
                      responses: mfaEvent.prompts.map(() => ""),
                    });
                  }}
                >
                  取消
                </button>
                <button type="submit" className="password-retry-btn retry">
                  验证
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
});
